### ISSUE TITLE
errors when using calcium in mixtures

### ISSUE THREAD

**Issue by CoolFact** [CalebBell/thermo#116]
I have trouble getting calcium based components to work in the mixture library, here is the Traceback for milk of lime:
```
Traceback (most recent call last):
  File "path\VLE\chemprop.py", line 49, in <module>
    mix = Mixture(['water', 'Ca(OH)2'], Vfls=[.6, .4], T=300, P=1E5)
  File "path\Python\Python39\lib\site-packages\thermo\mixture.py", line 608, in __init__
    self.zs = Vfs_to_zs(Vfs, Vms_TP)
  File "path\Python\Python39\lib\site-packages\chemicals\utils.py", line 1519, in Vfs_to_zs
    v = Vfs[i]/Vms[i]
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by CalebBell** [comment]
Hi,
There isn't enough data to work with that compound in Thermo, unfortunately.

**Comment by CoolFact** [comment]
I see,

is there a way to add the missing data manually?
